MODWRKFLOW-73: Delete all sub-nodes when deleting a workflow.
Add a new DTO with associated unit test for providing the ID and nodes.

Get the nodes from this workflow and delete those first.

The database structure is generated and there is no repo or anything like that to directly call for deletion.
The nodes are not associated with foreign keys in the database across all fields.
The `ON DELETE CASCADE` behavior is not useful, except for the embeddables.

Add on delete actions defaults where possible.

Avoid addng `@ManyToOne` or `@OneToMany` to avoid possible regressions, such as performance regressions.
The goal here is not to redesign the database structure.

Use the entity manager to perform custom **SQL** that shall perform the deletions.
The list of nodes on the **Workflow** is not the complete list of nodes.
Therefore, each entity that has a `_nodes` table must also be recursively parsed.

Use existing code to help build and dynamically construct the appropriate **SQL**.
The `DeserializeAsNodeJsonResolver.CLASSES` should probably be move to another class.
Doing so would introduce more changes than desired for now so this is avoided.

Add a debug logger to make the deletions easier to confirm/deny.

Remove the invalid/outdated comment "To be removed. This is just an experiment.".

Add `@Transactional` to the delete function in `WorkflowEngineService`.

For **Spring Boot 3**, Add `entityManager.clear();` to prevent errors like:
> StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) after using entitymanager to execute explicit delete query